name: biosig_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - ipython
  - numpy
  - matplotlib
  - mne
  - mne-icalabel
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytorch
  - pywavelets
  - scikit-learn
  - scipy
  - pyserial
  - tqdm
  - pynput
  - pip:
      - notebook
      - python-dotenv